sudo: required
services:
  - docker

before_install:
  - docker build -t abhi248/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhi248/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-439367053525"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY